name: Test Service 1.1 (Beta)
on:
  schedule:
    #NY 23:00pm
    - cron: '*/20 * * * *'
    #- cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: dev
    env:
      #for build only
      EC_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TKN}}      
      EC_BUILD_ID: ${{ github.run_number }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Launch Service 1.1 (Beta)
        run: chmod +x ./test/e2e.sh && ./test/e2e.sh
            
