name: Test Service 1.1 (Beta)
on:
  workflow_dispatch:
  #push:
  #  branches: [ 0.1-b.1, main ]
  #pull_request:
  #  branches: [ 0.1-b.1, main ]
  #  types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: dev
    env:
      EC_SVC_ID: my-test-id
      EC_SVC_URL: my-test-url
      EC_ADM_TKN: my-legacy-cf-admin-token
      EC_SAC_DN: ${{secrets.EC_SAC_DN}}
      EC_ATH_DN: ${{secrets.EC_ATH_DN}}
      EC_CID: ${{secrets.EC_CID}}
      EC_CSC: ${{secrets.EC_CSC}}
      EC_SCRIPT_1: ${{secrets.EC_SCRIPT_1}}
      EC_SCRIPT_2: ${{secrets.EC_SCRIPT_2}}
      EC_SCRIPT_3: ${{secrets.EC_SCRIPT_3}}
    steps:
      - uses: actions/checkout@v2
      - name: Launch Service 1.1 (Beta)
        run: |
          #
          cat << EOF
          -------------------------------------
          [1] mockup legacy setting
          -------------------------------------
          EOF
          
          EC_SETTING=$(echo '{"my-test-id":{"ids":["my-aid-1","my-aid-2"],"trustedIssuerIds":["legacy-cf-uaa-url"]}}' | base64 -w0)      
 
          cat << EOF
          -------------------------------------
          [2] launch service instance
          -------------------------------------
          EOF
          
          mkdir -p ./svcs
          docker run --name=svc \
          -e EC_SVC_ID=$EC_SVC_ID \
          -e EC_SVC_URL=$EC_SVC_URL \
          -e EC_ADM_TKN=$EC_ADM_TKN \
          -e EC_SAC_DN=$EC_SAC_DN \
          -e EC_ATH_DN=$EC_ATH_DN \
          -e EC_CID=$EC_CID \
          -e EC_CSC=$EC_CSC \
          -e EC_SETTING=$EC_SETTING \
          -e EC_SCRIPT_1=$EC_SCRIPT_1 \
          -e EC_SCRIPT_2=$EC_SCRIPT_2 \
          -e EC_SCRIPT_3=$EC_SCRIPT_3 \
          -v $(pwd)/svcs:/root/svcs \
          -d \
          ghcr.io/ec-release/service:v1.1
          
          sleep 10
          cat << EOF
          -------------------------------------
          [3] verify serialised service setting 
          -------------------------------------
          EOF
          
          tree ./svcs
          cat ./svcs/$EC_SVC_ID.json
