name: Test Service 1.1 (Beta)
on:
  schedule:
    #NY 23:00pm
    - cron: '0 3 * * *'
  workflow_dispatch:
  #push:
  #  branches: [ 0.1-b.1, main ]
  #pull_request:
  #  branches: [ 0.1-b.1, main ]
  #  types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: dev
    env:
      EC_SVC_ID: my-test-id
      EC_SVC_URL_PUB: my-test-public-url
      #e.g. urlhttp://svc-id.ec-engineering.svc.cluster.local:18090
      EC_SVC_URL_NAT: my-test-nat-url
      EC_ADM_TKN: my-legacy-cf-admin-token
      #e.g. http://localhost:8080
      EC_SAC_URL: ${{secrets.EC_SAC_URL}}
      EC_ATH_URL: ${{secrets.EC_ATH_URL}}
      EC_CID: ${{secrets.EC_CID}}
      EC_CSC: ${{secrets.EC_CSC}}
      EC_SCRIPT_1: ${{secrets.EC_SCRIPT_1}}
      EC_SCRIPT_2: ${{secrets.EC_SCRIPT_2}}
      EC_SCRIPT_3: ${{secrets.EC_SCRIPT_3}}
      EC_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TKN}}
    steps:
      - uses: actions/checkout@v2
      - name: Launch Service 1.1 (Beta)
        run: chmod +x ./test/e2e.sh && ./test/e2e.sh
        #run: |
        #  timeout --version
        #  timeout 2 ping localhost
            
