name: Test Service 1.1 (Beta)
on:
  workflow_dispatch:
  #push:
  #  branches: [ 0.1-b.1, main ]
  #pull_request:
  #  branches: [ 0.1-b.1, main ]
  #  types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: beta
    env:
      EC_SVC_ID: my-test-id
      EC_SVC_URL: my-test-url
      EC_SAC_URL: my-sac-url
      EC_ATH_URL: my-ath-url
      EC_CID: ${{secrets.EC_CID}}
      EC_CSC: ${{secrets.EC_CSC}}
      EC_PVK: my-test-key
      EC_CER: my-test-cer
    steps:
      - uses: actions/checkout@v2
      #- uses: actions-rs/toolchain@v1
      #  with:
      #    toolchain: nightly #stable
      #    override: true
      - name: Building Service 1.1 (Beta)
        run: |
          docker run \
          -e EC_SVC_ID=$EC_SVC_ID \
          -e EC_SVC_URL=$EC_SVC_URL \
          -e EC_SAC_URL=$EC_SAC_URL \
          -e EC_ATH_URL=$EC_ATH_URL \
          -e EC_CID=$EC_CID \
          -e EC_CSC=$EC_CSC \
          -e EC_PVK=$EC_PVK \
          -e EC_CER=$EC_CER \
          ghcr.io/ec-release/service:v1.1
